// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBvbvAve-uY4rMbo1vSOagZ_qNnv9_sEs',
    appId: '1:671890704911:web:73453636cfced6485fb17a',
    messagingSenderId: '671890704911',
    projectId: 'learning-firebase-2edb1',
    authDomain: 'learning-firebase-2edb1.firebaseapp.com',
    storageBucket: 'learning-firebase-2edb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWqZB5UWueYzcJsrx1LMMUPYYi_6E9X10',
    appId: '1:671890704911:android:c77427100576cbf25fb17a',
    messagingSenderId: '671890704911',
    projectId: 'learning-firebase-2edb1',
    storageBucket: 'learning-firebase-2edb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVMjPhJtQuJi_ISff2LdajdGOtPoOWNDc',
    appId: '1:671890704911:ios:f47b311a308fff965fb17a',
    messagingSenderId: '671890704911',
    projectId: 'learning-firebase-2edb1',
    storageBucket: 'learning-firebase-2edb1.firebasestorage.app',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVMjPhJtQuJi_ISff2LdajdGOtPoOWNDc',
    appId: '1:671890704911:ios:f47b311a308fff965fb17a',
    messagingSenderId: '671890704911',
    projectId: 'learning-firebase-2edb1',
    storageBucket: 'learning-firebase-2edb1.firebasestorage.app',
    iosBundleId: 'com.example.todoAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBvbvAve-uY4rMbo1vSOagZ_qNnv9_sEs',
    appId: '1:671890704911:web:e70e87203b6079ff5fb17a',
    messagingSenderId: '671890704911',
    projectId: 'learning-firebase-2edb1',
    authDomain: 'learning-firebase-2edb1.firebaseapp.com',
    storageBucket: 'learning-firebase-2edb1.firebasestorage.app',
  );
}